config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root to: 'pages#home'
  get '/pick_type', to: 'pages#pick_type'
  get '/new', to: 'pages#new'
  get '/professors', to: 'pages#professors'
  get '/professors/:id', to: 'pages#professor_show'
  get '/about_us', to: 'pages#about_us'
  get '/services', to: 'pages#services'
  get '/testimonies', to: 'pages#testimonies'
  get '/how_it_works', to: 'pages#how_it_works'
  get '/contact-us', to: 'pages#contact_us'
  get '/check-email', to: 'pages#check_email'
  get '/how-it-works', to: 'pages#how_it_works'
  get '/pricing', to:'pages#pricing'
  # get '/change-theme', to: 'application#set_theme'
  resources :contacts, only: [:create]

  resources :qnas do
    get :pick_type, on: :collection
    put :finish
    get :cancel
    resources :chats, only: [:show] do
      resources :messages, only: [:create], on: :collection
    end
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/auth/sessions',
    registrations: 'admins/auth/registrations',
    passwords: 'admins/auth/passwords'
  }

  devise_for :tutors, path: 'tutors', controllers: {
    sessions: 'tutors/auth/sessions',
    registrations: 'tutors/auth/registrations',
    passwords: 'tutors/auth/passwords'
  }

  devise_for :managers, path: 'managers', controllers: {
    sessions: 'managers/auth/sessions',
    registrations: 'managers/auth/registrations',
    passwords: 'managers/auth/passwords'
  }

  devise_for :accountants, path: 'accountants', controllers: {
    sessions: 'accountants/auth/sessions',
    registrations: 'accountants/auth/registrations',
    passwords: 'accountants/auth/passwords'
  }

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/auth/sessions',
    registrations: 'users/auth/registrations',
    passwords: 'users/auth/passwords'
  }

  devise_for :quality_officers, path: 'quality_officers', controllers: {
    sessions: 'quality_officers/auth/sessions'
    # registrations: 'quality_officers/auth/registrations',
    # passwords: 'quality_officers/auth/passwords'
  }

  namespace :admins do
    resources :homeworks, except: [:new, :create], on: :collection do
      put :assign
      put :finish_homework
      put :assign_tutor
      post :upload
    end
    resources :professors
    resources :prof_reviews, only: [:show, :update] do
      post :approve
    end
    resources :documents, only: [:index], on: :collection
    resources :managers, on: :collection
    resources :users, on: :collection
    resources :tutors, on: :collection
    resources :accountants, on: :collection
    resources :admins
    resources :chats, only: [:index]
    resources :quality_officers, on: :collection
    resources :qnas, only: [:index, :show], on: :collection do
      get :finish
    end
    get '/', to: 'dashboard#home'
  end

  namespace :quality_officers do
    resources :homeworks, only: [:index, :show] do
      post :upload
    end
    get '/', to: 'dashboard#home'
  end

  namespace :managers do
    resources :homeworks, only: [:index, :show, :update, :edit], on: :collection do
      post :upload
      put :approve
      put :assign_tutor
    end
    resources :chats, only: [:index]
    get '/', to: 'dashboard#home'
  end

  namespace :tutors do
    resources :homeworks, only: [:index, :show], on: :collection do
      get :add_bid
      get :edit_bid
      post :bid
      put :update_bid
      post :upload
      put :finish_homework
    end

    resources :qnas, only: [:index, :show] do
      put :assign
      put :cancel

      resources :messages, only: [:create]
      patch '/add_payment', to: 'qnas#add_payment', as: 'add_payment'
    end

    resources :chats, only: [:index]
    get '/', to: 'homeworks#index'
  end

  namespace :users do
    resources :homeworks, on: :collection do
      get :success
      get :pick_type, on: :collection

      patch '/edit', to: 'homeworks#update', as: 'update_homework'
      get '/submit_homework', to: 'homeworks#submit_homework', as: 'submit_homework'

      get '/delete_draft', to: 'homeworks#delete_draft', as: 'delete_draft'
    end
    post 'homeworks/add_to_draft', to: 'homeworks#add_to_drafts', as: 'add_to_drafts'

    resources :professors, only: [:index, :show, :new, :create] do
      get :search, on: :collection
    end

    resources :qnas do
      get :finish
      get :cancel
      resources :chats, only: [:show] do
        resources :messages, only: [:create], on: :collection
      end
    end

    get 'profile', to: 'users#show'
    resources :chats, only: [:index]
    get '/', to: 'dashboard#home'
  end

  namespace :accountants do
    resources :homeworks, only: [:index, :show, :update], on: :collection
    get '/', to: 'dashboard#home'
  end
  get '/cheko-ai' => 'gpt3#index'
  post '/gpt3/generate' => 'gpt3#generate'
  post '/gpt3/rewrite' => 'gpt3#rewrite'
  post '/gpt3/humanize' => 'gpt3#humanize'
  post '/gpt3/update_title' => 'gpt3#update_title'
  post '/gpt3/update_conversation' => 'gpt3#update_conversation'
  post '/gpt3/save_conversation' => 'gpt3#save_conversation'
  post '/gpt3/delete_conversation' => 'gpt3#delete_conversation'
  get '/gpt3/render_better_answer_bubble' => 'gpt3#render_better_answer_bubble'
end

app/controllers/admins/users_controller.rb
class Admins::UsersController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_user, except: [:index, :new, :create]

  def index
    @users = User.all
  end

  def show
  end

  def edit
  end

  def update
    if @user.update(user_params)
      redirect_to admins_user_path(@user), notice: "User successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    @user.destroy!
    redirect_to admins_users_path, notice: "User successfully deleted"
  end

  private

  def find_user
    @user = User.find(params[:id])
  end

  def user_params
    params.require(:user).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/users/chats_controller.rb
class Users::ChatsController < ApplicationController
  before_action :authenticate_user!
  
  def show
  end

  def destroy
  end
end

app/controllers/users/dashboard_controller.rb
class Users::DashboardController < Users::UserAppController
  before_action :authenticate_user!
  
  def home
  end
end

app/controllers/users/homeworks_controller.rb
class Users::HomeworksController < Users::UserAppController
  before_action :authenticate_user!
  before_action :find_homework, except: [:index, :create, :new, :pick_type, :add_to_drafts]
  
  def index
    # @pending = current_user.homeworks.where(status: "reviewing")
    # @ongoing = current_user.homeworks.where(status: "ongoing")
    # @history = current_user.homeworks.where(status: "done")
    @homeworks = current_user.homeworks.not_deleted
  end

  def show
    @tutor = @homework.documents.where(documentable_type: "Tutor")
    @qco = @homework.documents.where(documentable_type: "QualityOfficer")
    @admin = @homework.documents.where(documentable_type: "Admin")
    @manager = @homework.documents.where(documentable_type: "Manager")
  end

  def new
    if params[:type].blank?
      redirect_to pick_type_users_homeworks_path
    else
      @homework = current_user.homeworks.new()
    end
  end

  def create
    @admin = Admin::where(role: 1, status: 1).first
    @homework = current_user.homeworks.new(homework_params)

    if @homework.save
      #assign admin_id
      @homework.update(admin_id: @admin.id)

      HomeworkMailerJob.set(wait: 2.seconds).perform_later(@homework, "NewOrder")
      # HomeworkMailerJob.set(wait: 2.seconds).perform_later(@homework, "Admin")

      # team_managers = Manager.all
      # team_managers.each do |team_manager|
      #   NotifyTmMailerJob.set(wait: 2.seconds).perform_later("new_order", team_manager)
      # end

      HomeworkMailerJob.set(wait: 2.seconds).perform_later(@homework, "BookedOrder")

      ActionCable.server.broadcast 'homework_update_channel', data: { homework: {
          id: @homework.id, 
          created_at: @homework.created_at.strftime("%b %d, %Y"), order_type: @homework.order_type.titleize, 
          sub_type: @homework.sub_type.present? ? @homework.sub_type.titleize : "", 
          deadline: @homework.deadline.present? ? @homework.deadline.strftime("%b %d, %Y - %l:%M %p"): "",  
          subject: @homework.subject.present? ? @homework.subject.titleize : "",
          tutor_category: @homework.tutor_category.present? ? @homework.tutor_category.titleize : "",
          words: @homework.words.present? ? @homework.words : "",
          tutor_samples: @homework.tutor_samples.present? ? @homework.tutor_samples.to_s.capitalize : "False",
          tutor_skills: @homework.tutor_skills.present? ? @homework.tutor_skills.to_s.capitalize : "False",
          view_bidders: @homework.view_bidders.present? ? @homework.view_bidders.to_s.capitalize : "False",
          priority: @homework.priority.present? ? @homework.priority.to_s.capitalize : "False",
          login_school: @homework.login_school.present? ? @homework.login_school.to_s.capitalize : "False",
          admin_id: @homework.admin_id,
          admin: @homework.admin.name,
          name: @homework.name.present? ? @homework.name : "",
          order_type: @homework.order_type.titleize,
          internal_deadline_date: @homework.internal_deadline.present? ? @homework.internal_deadline.strftime("%B %d, %Y") : "",
          internal_deadline_time: @homework.internal_deadline.present? ? @homework.internal_deadline.strftime("%l:%M %p") : "",
          details: @homework.details.present? ? @homework.details : "",
          user: @homework.user.present? ? @homework.user.name : "",
          tutor: @homework.tutor.present? ? @homework.tutor.name : "",
          sub_tutor: @homework.sub_tutor.present? ? @homework.sub_tutor.name : "",
          hours_late: @homework.hours_late.present? ? @homework.hours_late : "",
          prof: @homework.prof.present? ? @homework.prof : "",
          grade: @homework.grade.present? ? @homework.grade : "",
          status: @homework.status.present? ? @homework.status : "",
          manager: @homework.manager.present? ? @homework.manager.name : "",
          tutor_price: @homework.tutor_price.present? ? @homework.tutor_price : "",
          price: @homework.price.present? ? @homework.price : "",
          profit: @homework.profit.present? ? @homework.profit : "",
          updates: @homework.updates.present? ? @homework.updates : "",
          sub_subject: @homework.sub_subject.present? ? @homework.sub_subject : "",
          file_received: @homework.file_received.present? ? @homework.file_received : "",
          notes: @homework.notes.present? ? @homework.notes : "",
          course: @homework.user.present? ? @homework.user.course : "",
          payment_received: @homework.payment_received.present? ? @homework.payment_received : "",
          } },
      controller_action: "create"

      redirect_to users_homework_path(@homework.id), :alert => "Thanks for your order! Kindly message us through our chatbox on the lower right corner to confirm the price!"
    else
      render 'new'
    end
  end

  def success
    unless @homework.user_id == current_user.id
      redirect_to users_homeworks_path
    end
  end

  def edit
  end

  def update
    if @homework.update!(homework_params)
      redirect_to users_homeworks_path
    else
      render 'edit'
    end
  end

  def destroy
  end

  def add_to_drafts
    @homework = current_user.homeworks.new(homework_params)
    if @homework.save
      @homework.update(status: "in_draft")
      redirect_to users_homeworks_path
    else
      redirect_to new_users_homework_path
    end
  end

  def submit_homework
    @admin = Admin::where(role: 1, status: 1).first
    @homework = Homework.update(@homework.id, status: "reviewing", admin_id: @admin.id)

    HomeworkMailerJob.set(wait: 2.seconds).perform_later(@homework, "NewOrder")
    #send email all tutors that new homework is up for bidding
  
    HomeworkMailerJob.set(wait: 2.seconds).perform_later(@homework, "BookedOrder")

    redirect_to users_homeworks_path
  end

  def delete_draft
    @homework = Homework.find(params[:homework_id])
    @homework.soft_delete
    @homework.update(status: "deleted", deleted_at: DateTime.now)
    redirect_to users_homeworks_path
  end

  private 

  def find_homework
    @homework = Homework.find(params[:id] || params[:homework_id])
  end

  def homework_params
    if params[:homework][:deadline].blank?
      deadline = DateTime.now
    else
      deadline = DateTime.strptime(params[:homework][:deadline], "%m/%d/%Y, %I:%M %p")
    end
    params.require(:homework).permit(:details, :payment_type, :subject, :sub_subject, :budget, :tutor_skills, :tutor_samples, :sub_type, :priority, :view_bidders, :login_school, :budget, :order_type, :words, :tutor_category, :hw_attachment => []).merge(deadline: deadline)
  end
end

app/controllers/users/messages_controller.rb
class Users::MessagesController < ApplicationController
  before_action :authenticate_user!

  def create
    chat = Chat.find(params[:chat_id])
    qna = Qna.find(params[:qna_id])

    if current_user.id == qna.user_id
      message = Message.new(content: params[:message][:content], chat_id: chat.id, document: params[:message][:document], sendable_type: "User")
      if message.save
        SendMessageJob.perform_now(message, "User", chat.id, { document_url: message.document.attached? ? rails_blob_path(message.document, disposition: 'attachment') : nil })
      else
        SendMessageJob.perform_now(message, "Error User", chat.id, { message: message.errors.full_messages, document_url: message.document.attached? ? rails_blob_path(message.document, disposition: 'attachment') : nil })
      end
    end
  end

  def destroy
  end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/qnas_controller.rb
class Users::QnasController < Users::UserAppController
  before_action :authenticate_user!
  
  def index
    @qnas = current_user.qnas.where("status = 0 OR status = 1")
    @finish = current_user.qnas.where(status: "done")
  end

  def new
    @qna = current_user.qnas.new
    # if qna_old = Qna.find_by(auth: cookies[:tutor_qna])
    #   redirect_to users_qna_path(qna_old.id)
    # else
    #   @qna = current_user.qnas.new
    # end
  end

  def create
    @qna = current_user.qnas.create(qna_params)
    cookies[:tutor_qna] = @qna

    redirect_to users_path 
  end

  def show 
    @qna = Qna.find(params[:id])
    @message = Message.new
  end

  def finish
    @qna = Qna.find(params[:qna_id])
    @qna.update(status: "done")

    redirect_to users_path
  end

  def cancel
    @qna = Qna.find(params[:qna_id])
    @qna.update(status: "cancelled")

    redirect_to users_path
  end

  private

  def qna_params
    params.require(:qna).permit(:question, :subject,document_attachments: [])
  end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/helpers/admins/users_helper.rb
module Admins::UsersHelper
end

app/helpers/users/chats_helper.rb
module Users::ChatsHelper
end

app/helpers/users/dashboard_helper.rb
module Users::DashboardHelper
end

app/helpers/users/homeworks_helper.rb
module Users::HomeworksHelper
end

app/helpers/users/messages_helper.rb
module Users::MessagesHelper
end

app/helpers/users/professors_helper.rb
module Users::ProfessorsHelper
  def options_for_school
    options = School.all.collect {|p| [ p.name, p.id ] }
    options << ['Others', 'others']
    # you can define your own logic for selected value.
    selected = !@professor.nil? ? @professor.school_id : 1
    options_for_select(options, selected)
  end
end

app/helpers/users/q_n_as_helper.rb
module Users::QNAsHelper
end

app/views/users/shared/_chat-widget.html.haml
:javascript
  window.addEventListener("chatwoot:ready", function () { 
    var emailUser = '#{current_user.email}'
    var nameUser = '#{current_user.name}'
    var hasssh = '#{current_user.identifier_string}'
    var identifier = '#{current_user.id}-client'
  //  window.$chatwoot.setUser('#{current_user.email}', {
  //    name: '#{current_user.name}',
  //    email: '#{current_user.email}',
  //    phone_number: '',
  //    avatar_url: '',
  //    identifier_hash: '#{current_user.identifier_string}',
  //    social_profiles: {
  //      github: "Bret-koda", // Github user name
  //    },
  //  });

    window.$chatwoot.setUser(identifier, {
      email: emailUser,
      name: nameUser,
      identifier_hash: hasssh,
    });

    window.$chatwoot.setCustomAttributes({
      accountId: '#{current_user.id}-client',
      note: "THIS IS A TEST NOTE",
    });
  });

  /*window.chatwootSettings = {
    type: "expanded_bubble",
    launcherTitle: "Chat with us",
  };*/

  window.chatwootSettings = {
    position: "left",
    type: "standard",
    launcherTitle: "",
  };
  
  
  (function(d,t) {
    var BASE_URL="https://chatwoot.chekohomeworkhelp.com";
    var g=d.createElement(t),s=d.getElementsByTagName(t)[0];
    g.src=BASE_URL+"/packs/js/sdk.js";
    g.defer = true;
    g.async = true;
    s.parentNode.insertBefore(g,s);
    g.onload=function(){
      window.chatwootSDK.run({
        websiteToken: '7RG6pzEtMjQ19aDaPze9vxnu',
        baseUrl: BASE_URL
      });
    }
  })(document,"script");

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_footer.html.haml
.container-fluid
  .container.text-white.text-center.pt-3.pb-4
    %a.text-white{href: about_us_path} About Us
    %a.text-white{href: contact_us_path} Contact Us
    %a.text-white{href: services_path} Services
    %a.text-white{href: testimonies_path} Testimonies
    %a.text-white{href: pricing_path} Pricing
.container-fluid.bg-cheko 
  .container.text-white.text-center
    %a.text-white{href: "https://www.facebook.com/chekoworks"}
      %i.fa-brands.fa-facebook{"aria-hidden" => "true"}
    %a.text-white{href: "https://www.instagram.com/chekoworks/"}
      %i.fa-brands.fa-instagram{"aria-hidden" => "true"}
    %a.text-white{href: "https://www.tiktok.com/@chekoworks"}
      %i.fa-brands.fa-tiktok{"aria-hidden" => "true"}
.container-fluid.bg-cheko 
  .container.text-white.pt-2.pb-2.text-center
    Copyright 2021 | All Rights Reserved | ChekoHomeworkHelp.com

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/shared/_sidebar.html.erb
<div class="flex flex-col h-screen sticky left-0 top-0 min-w-[280px] max-w-[280px] max-h-screen py-3 px-1 bg-sidebar-cheko overflow-y-auto">
  <%= link_to root_path, class: "grid justify-items-center w-full mb-1 no-underline" do %>
    <div class="flex flex-col">
      <div class="flex">
        <%= image_tag "logo-white.png", class: "h-7 mt-1" %>
        <div class="text-zinc-500 font-semibold text-4xl italic">AI</div>
      </div>
    </div>
  <% end %>
  <div class="grid w-full mt-[1rem]">
    <%= render "users/shared/sidebar_item", title: "Home", path: root_path, icon: "home" %>
    <%= render "users/shared/sidebar_item", title: "HW Help", path: pick_type_path, icon: "pen" %>
    <%= render "users/shared/sidebar_item", title: "Profs to Pick", path: professors_path, icon: "chalkboard-user" %>
    <%= render "users/shared/sidebar_convo_item", title: "Convo", icon: "comments" %>
  </div>
  <div class="grid px-2.5 w-full my-3 flex h-full">
      <a href="<%= cheko_ai_path %>" class="p-2 py-2 text-white bg-new-cheko-2 new-convo-btn rounded-md mt-auto text-base font-extrabold text-center">
        <i class="fa-regular fa-comments text-md me-1"></i>
        <span>New convo</span>
      </a>
  </div>
  <div>
    <a href="https://airtable.com/app0IcnuLWamJOjoO/pagglD74lTU003e8O/form" target="_blank" class="pl-2 pr-1 py-2 cheko-text-1 new-convo-btn rounded-md mt-auto text-xs">
      <i class="fa-solid fa-download text-md me-1"></i>
      <span>Cheko Mobile</span>
    </a>
    <div class="check-button-divider-1"></div>

    <a href="https://airtable.com/app0IcnuLWamJOjoO/pagglD74lTU003e8O/form" target="_blank" class="p-2 py-2 cheko-text-1 new-convo-btn rounded-md mt-auto text-xs">
      <i class="fa-brands fa-chrome text-md me-1"></i>
      <span>Cheko for Chrome</span>
    </a>
  </div>
</div>

app/views/users/shared/_sidebar_convo_item.html.erb
<div>
  <%= content_tag :div, class: "text-neutral-500 hover:text-neutral-500 rounded-md  font-semibold flex gap-2 items-center py-2.5 px-[1rem] no-underline hover:bg-neutral-700/30" do %>
    <%= icon('fa-regular', icon, class: "text-lg")%> <%= title %>
  <% end %>
  <div id="conversation-list" class="divide-x-[3px] divide-solid divide-neutral-700 text-neutral-500 text-sm font-semibold items-center py-1 pr-3 pl-8 no-underline ">
    <% if user_signed_in? %>
      <% current_user.conversations.order(created_at: :DESC).each do |conversation| %>
        <div class="flex justify-between my-2 hover:bg-neutral-700/30 pr-2 sidebar-conversation-item-list">
          <a href="<%= cheko_ai_path(conversation_id: conversation.id) %>" id="conversation-list-<%= conversation.id %>" class="pl-2 max-w-[200px] w-full py-1 block my-2 truncate"><%= conversation.title_name %></a>
          <button style="display: none;" class="delete_conversation_btn" data-conversation_id="<%= conversation.id %>">
            <i class="fa-solid fa-trash-can"></i>
          </button>
        </div>
      <% end %>
    <% end %>
    <a href="<%= cheko_ai_path %>" class="pl-2 hover:bg-neutral-700/30 w-full py-1 block my-2">New Convo</a>
  </div>
</div>

app/views/users/shared/_sidebar_item.html.erb
<%= link_to path, class: "#{current_page?(path) ? "bg-neutral-700/30 text-white visited:text-white" : "text-neutral-500 hover:text-white"} rounded-md  font-semibold flex gap-2 items-center py-2.5 px-[1rem] no-underline hover:bg-neutral-700/30" do %>
  <%= icon('fa-solid', icon, class: "w-5")%> <%= title %>
<% end %>