config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root to: 'pages#home'
  get '/pick_type', to: 'pages#pick_type'
  get '/new', to: 'pages#new'
  get '/professors', to: 'pages#professors'
  get '/professors/:id', to: 'pages#professor_show'
  get '/about_us', to: 'pages#about_us'
  get '/services', to: 'pages#services'
  get '/testimonies', to: 'pages#testimonies'
  get '/how_it_works', to: 'pages#how_it_works'
  get '/contact-us', to: 'pages#contact_us'
  get '/check-email', to: 'pages#check_email'
  get '/how-it-works', to: 'pages#how_it_works'
  get '/pricing', to:'pages#pricing'
  # get '/change-theme', to: 'application#set_theme'
  resources :contacts, only: [:create]

  resources :qnas do
    get :pick_type, on: :collection
    put :finish
    get :cancel
    resources :chats, only: [:show] do
      resources :messages, only: [:create], on: :collection
    end
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/auth/sessions',
    registrations: 'admins/auth/registrations',
    passwords: 'admins/auth/passwords'
  }

  devise_for :tutors, path: 'tutors', controllers: {
    sessions: 'tutors/auth/sessions',
    registrations: 'tutors/auth/registrations',
    passwords: 'tutors/auth/passwords'
  }

  devise_for :managers, path: 'managers', controllers: {
    sessions: 'managers/auth/sessions',
    registrations: 'managers/auth/registrations',
    passwords: 'managers/auth/passwords'
  }

  devise_for :accountants, path: 'accountants', controllers: {
    sessions: 'accountants/auth/sessions',
    registrations: 'accountants/auth/registrations',
    passwords: 'accountants/auth/passwords'
  }

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/auth/sessions',
    registrations: 'users/auth/registrations',
    passwords: 'users/auth/passwords'
  }

  devise_for :quality_officers, path: 'quality_officers', controllers: {
    sessions: 'quality_officers/auth/sessions'
    # registrations: 'quality_officers/auth/registrations',
    # passwords: 'quality_officers/auth/passwords'
  }

  namespace :admins do
    resources :homeworks, except: [:new, :create], on: :collection do
      put :assign
      put :finish_homework
      put :assign_tutor
      post :upload
    end
    resources :professors
    resources :prof_reviews, only: [:show, :update] do
      post :approve
    end
    resources :documents, only: [:index], on: :collection
    resources :managers, on: :collection
    resources :users, on: :collection
    resources :tutors, on: :collection
    resources :accountants, on: :collection
    resources :admins
    resources :chats, only: [:index]
    resources :quality_officers, on: :collection
    resources :qnas, only: [:index, :show], on: :collection do
      get :finish
    end
    get '/', to: 'dashboard#home'
  end

  namespace :quality_officers do
    resources :homeworks, only: [:index, :show] do
      post :upload
    end
    get '/', to: 'dashboard#home'
  end

  namespace :managers do
    resources :homeworks, only: [:index, :show, :update, :edit], on: :collection do
      post :upload
      put :approve
      put :assign_tutor
    end
    resources :chats, only: [:index]
    get '/', to: 'dashboard#home'
  end

  namespace :tutors do
    resources :homeworks, only: [:index, :show], on: :collection do
      get :add_bid
      get :edit_bid
      post :bid
      put :update_bid
      post :upload
      put :finish_homework
    end

    resources :qnas, only: [:index, :show] do
      put :assign
      put :cancel

      resources :messages, only: [:create]
      patch '/add_payment', to: 'qnas#add_payment', as: 'add_payment'
    end

    resources :chats, only: [:index]
    get '/', to: 'homeworks#index'
  end

  namespace :users do
    resources :homeworks, on: :collection do
      get :success
      get :pick_type, on: :collection

      patch '/edit', to: 'homeworks#update', as: 'update_homework'
      get '/submit_homework', to: 'homeworks#submit_homework', as: 'submit_homework'

      get '/delete_draft', to: 'homeworks#delete_draft', as: 'delete_draft'
    end
    post 'homeworks/add_to_draft', to: 'homeworks#add_to_drafts', as: 'add_to_drafts'

    resources :professors, only: [:index, :show, :new, :create] do
      get :search, on: :collection
    end

    resources :qnas do
      get :finish
      get :cancel
      resources :chats, only: [:show] do
        resources :messages, only: [:create], on: :collection
      end
    end

    get 'profile', to: 'users#show'
    resources :chats, only: [:index]
    get '/', to: 'dashboard#home'
  end

  namespace :accountants do
    resources :homeworks, only: [:index, :show, :update], on: :collection
    get '/', to: 'dashboard#home'
  end
  get '/cheko-ai' => 'gpt3#index'
  post '/gpt3/generate' => 'gpt3#generate'
  post '/gpt3/rewrite' => 'gpt3#rewrite'
  post '/gpt3/humanize' => 'gpt3#humanize'
  post '/gpt3/update_title' => 'gpt3#update_title'
  post '/gpt3/update_conversation' => 'gpt3#update_conversation'
  post '/gpt3/save_conversation' => 'gpt3#save_conversation'
  post '/gpt3/delete_conversation' => 'gpt3#delete_conversation'
  get '/gpt3/render_better_answer_bubble' => 'gpt3#render_better_answer_bubble'
end

app/controllers/accountants/homeworks_controller.rb
class Accountants::HomeworksController < ApplicationController
  before_action :authenticate_accountant!
  before_action :find_homework, except: [:index]
  
  def index
    @pending = Homework.where(payment_status: "unpaid").order(created_at: :desc)
    @history = Homework.where(payment_status: "paid").order(created_at: :desc)
  end

  def update
    @homework.approve_payment
    redirect_to accountants_homeworks_path
  end

  private 

  def find_homework
    @homework = Homework.find(params[:id] || params[:homework_id])
  end
end

app/controllers/admins/homeworks_controller.rb
class Admins::HomeworksController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_homework, except: [:index]

  def index
    @history = current_admin.role == "admin" ? Homework.where(status: "done", admin_id: current_admin.id).order(created_at: :asc) : Homework.where(status: "done").order(created_at: :asc)
    @pending = Homework.where(status: "reviewing", admin_id: current_admin.id)
    @ongoing = current_admin.role == "admin" ? Homework.where(status: "ongoing", admin_id: current_admin.id) : Homework.where(status: "ongoing")
    # @ongoing = Homework.find_by_sql("SELECT * FROM homeworks WHERE status IN(2,6) AND admin_id = #{current_admin.id}") 
    @finished_by_tutor = Homework.where(status: "finished_by_tutor", admin_id: current_admin.id)
  end

  def show
    @bids = Bid.where(homework_id: @homework.id).order(ammount: :asc)
    @tutor = @homework.documents.where(documentable_type: "Tutor")
    @qco = @homework.documents.where(documentable_type: "QualityOfficer")
    @admin = @homework.documents.where(documentable_type: "Admin")
  end

  def destroy
    @homework.destroy!
    redirect_to admins_homeworks_path, alert: "Homework successfully deleted"
  end

  def edit
    @leads = Admin.all
    @managers = Manager.all.not_deleted
    @tutors = Tutor.all
  end

  def update

    work = @homework.update(homework_params.to_h)
    
    if params[:homework][:internal_deadline].present?
      internal_deadline = DateTime.strptime(params[:homework][:internal_deadline], "%m/%d/%Y, %I:%M %p")
    else
      internal_deadline = DateTime.now - 1.day
    end
    @homework.update(internal_deadline: internal_deadline)

    if work && @homework.admin_id.present? && @homework.status == "reviewing"
      @homework.accept_order

      #send email all tutors that new homework is up for bidding
      tutors = Tutor.all 
      tutors.each do |tutor|
        NotifyTutorJob.set(wait: 2.seconds).perform_later("new_order", tutor, @homework)
      end
    end

    if params[:homework][:tutor_price].present?
      @homework.assign_tutor(nil, params[:homework][:tutor_price].to_i)
    end

    ActionCable.server.broadcast 'homework_update_channel', data: { homework: {
      id: @homework.id, 
      created_at: @homework.created_at.strftime("%b %d, %Y"), order_type: @homework.order_type.titleize, 
      sub_type: @homework.sub_type.present? ? @homework.sub_type.titleize : "", 
      deadline: @homework.deadline.present? ? @homework.deadline.strftime("%b %d, %Y - %l:%M %p"): "",  
      subject: @homework.subject.present? ? @homework.subject.titleize : "",
      tutor_category: @homework.tutor_category.present? ? @homework.tutor_category.titleize : "",
      words: @homework.words.present? ? @homework.words : "",
      tutor_samples: @homework.tutor_samples.present? ? @homework.tutor_samples.to_s.capitalize : "",
      tutor_skills: @homework.tutor_skills.present? ? @homework.tutor_skills.to_s.capitalize : "",
      view_bidders: @homework.view_bidders.present? ? @homework.view_bidders.to_s.capitalize : "",
      priority: @homework.priority.present? ? @homework.priority.to_s.capitalize : "",
      login_school: @homework.login_school.present? ? @homework.login_school.to_s.capitalize : "",
      admin_id: @homework.admin_id,
      admin: @homework.admin.name,
      name: @homework.name.present? ? @homework.name : "",
      order_type: @homework.order_type.titleize,
      internal_deadline_date: @homework.internal_deadline.present? ? @homework.internal_deadline.strftime("%B %d, %Y") : "",
      internal_deadline_time: @homework.internal_deadline.present? ? @homework.internal_deadline.strftime("%l:%M %p") : "",
      details: @homework.details.present? ? @homework.details : "",
      user: @homework.user.present? ? @homework.user.name : "",
      tutor: @homework.tutor.present? ? @homework.tutor.name : "",
      sub_tutor: @homework.sub_tutor.present? ? @homework.sub_tutor.name : "",
      hours_late: @homework.hours_late.present? ? @homework.hours_late : "",
      prof: @homework.prof.present? ? @homework.prof : "",
      grade: @homework.grade.present? ? @homework.grade : "",
      status: @homework.status.present? ? @homework.status : "",
      manager: @homework.manager.present? ? @homework.manager.name : "",
      tutor_price: @homework.tutor_price.present? ? @homework.tutor_price : "",
      price: @homework.price.present? ? @homework.price : "",
      profit: @homework.profit.present? ? @homework.profit : "",
      updates: @homework.updates.present? ? @homework.updates : "",
      sub_subject: @homework.sub_subject.present? ? @homework.sub_subject : "",
      file_received: @homework.file_received.present? ? @homework.file_received : "",
      notes: @homework.notes.present? ? @homework.notes : "",
      course: @homework.user.present? ? @homework.user.course : "",
      payment_received: @homework.payment_received.present? ? @homework.payment_received : "",
      } }, controller_action: "update"

    redirect_to admins_homeworks_path, notice: "Homework successfully updated"
  end

  def assign
    if @homework.internal_deadline.blank?
      internal_deadline = DateTime.now - 1.day
    end
   
    @homework.update(admin_id: current_admin.id, internal_deadline: internal_deadline)
    @homework.accept_order

    #send email all tutors that new homework is up for bidding
    tutors = Tutor.all 
    tutors.each do |tutor|
      NotifyTutorJob.set(wait: 2.seconds).perform_later("new_order", tutor, @homework)
    end

    redirect_to admins_homeworks_path #, notice: "Successfully assigned"
  end

  def assign_tutor
    bid = Bid.find(params[:bid_id])
    @homework.assign_tutor(bid)
    
    
    # if @homework.price.present? && @homework.tutor_price.present?
    #   @homework.calculate_profit
    # end
    if !@homework.name.present?
      name = "#{@homework.user.first_name[0,1].capitalize}#{@homework.user.last_name[0,1].capitalize}_#{@homework.subject}##{@homework.deadline.strftime("%b%m")}_#{@homework.tutor.first_name[0,1].capitalize}#{@homework.tutor.last_name[0,1].capitalize}"
      @homework.update(name: name)
    end
    
    tutor = Tutor.find(bid.tutor_id)
    NotifyTutorJob.set(wait: 2.seconds).perform_later("approved_bid", tutor, @homework)

    redirect_to admins_homeworks_path
  end

  def finish_homework
    @homework.finish_order
    HomeworkMailerJob.set(wait: 2.seconds).perform_later(@homework, "Finish")

    HomeworkMailerJob.set(wait: 2.seconds).perform_later(@homework, "ApprovedByManager")

    ActionCable.server.broadcast 'homework_update_channel', data: { homework: {
      id: @homework.id, 
      created_at: @homework.created_at.strftime("%b %d, %Y"), order_type: @homework.order_type.titleize, 
      sub_type: @homework.sub_type.present? ? @homework.sub_type.titleize : "", 
      deadline: @homework.deadline.present? ? @homework.deadline.strftime("%b %d, %Y - %l:%M %p"): "",  
      subject: @homework.subject.present? ? @homework.subject.titleize : "",
      tutor_category: @homework.tutor_category.present? ? @homework.tutor_category.titleize : "",
      words: @homework.words.present? ? @homework.words : "",
      tutor_samples: @homework.tutor_samples.present? ? @homework.tutor_samples.to_s.capitalize : "",
      tutor_skills: @homework.tutor_skills.present? ? @homework.tutor_skills.to_s.capitalize : "",
      view_bidders: @homework.view_bidders.present? ? @homework.view_bidders.to_s.capitalize : "",
      priority: @homework.priority.present? ? @homework.priority.to_s.capitalize : "",
      login_school: @homework.login_school.present? ? @homework.login_school.to_s.capitalize : "",
      admin_id: @homework.admin_id,
      admin: @homework.admin.name,
      name: @homework.name.present? ? @homework.name : "",
      order_type: @homework.order_type.titleize,
      internal_deadline_date: @homework.internal_deadline.present? ? @homework.internal_deadline.strftime("%B %d, %Y") : "",
      internal_deadline_time: @homework.internal_deadline.present? ? @homework.internal_deadline.strftime("%l:%M %p") : "",
      details: @homework.details.present? ? @homework.details : "",
      user: @homework.user.present? ? @homework.user.name : "",
      tutor: @homework.tutor.present? ? @homework.tutor.name : "",
      sub_tutor: @homework.sub_tutor.present? ? @homework.sub_tutor.name : "",
      hours_late: @homework.hours_late.present? ? @homework.hours_late : "",
      prof: @homework.prof.present? ? @homework.prof : "",
      grade: @homework.grade.present? ? @homework.grade : "",
      status: @homework.status.present? ? @homework.status : "",
      manager: @homework.manager.present? ? @homework.manager.name : "",
      tutor_price: @homework.tutor_price.present? ? @homework.tutor_price : "",
      price: @homework.price.present? ? @homework.price : "",
      profit: @homework.profit.present? ? @homework.profit : "",
      updates: @homework.updates.present? ? @homework.updates : "",
      sub_subject: @homework.sub_subject.present? ? @homework.sub_subject : "",
      file_received: @homework.file_received.present? ? @homework.file_received : "",
      notes: @homework.notes.present? ? @homework.notes : "",
      course: @homework.user.present? ? @homework.user.course : "",
      payment_received: @homework.payment_received.present? ? @homework.payment_received : "",
      } }, controller_action: "finish_homework"

    redirect_to admins_homeworks_path
  end

  def upload
    @homework.documents.create(file: params[:document][:file], documentable_id: current_admin.id, documentable_type: current_admin.class.name)
    HomeworkMailerJob.set(wait: 2.seconds).perform_later(@homework, "AdminUpload")
    redirect_to admins_homework_path(@homework.id)
  end

  private 

  def find_homework
    @homework = Homework.find(params[:id] || params[:homework_id])
  end

  def homework_params
    if params[:homework][:deadline].present?

app/controllers/admins/tutors_controller.rb
class Admins::TutorsController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_tutor, except: [:index, :new, :create]

  def index
    @tutors = Tutor.all
  end

  def show
    @ongoing = Homework.where("tutor_id = ? AND status = 2", @tutor.id)
    @history = Homework.where("tutor_id = ? AND status = 3", @tutor.id)
  end

  def new
    @tutor = Tutor.new
  end

  def create
    @tutor = Tutor.new(tutor_params)
    if @tutor.save
      @tutor.update!(status: 1)
      redirect_to admins_tutors_path, notice: "Tutor successfully created"
    else
      flash.now[:alert] = "Email is already been used"
      render 'new'
    end
  end

  def edit
  end

  def update
    if @tutor.update(tutor_params)
      redirect_to admins_tutor_path(@tutor), notice: "Tutor successfully updated"
    else
      render 'edit'
    end
  end

  def destroy
    
    Homework.where(tutor_id: @tutor.id).each do |hmw|
      hmw.update(tutor_id: nil)
    end
    
    @tutor.destroy!
    redirect_to admins_tutors_path, notice: "Tutor successfully deleted"
  end

  private 

  def find_tutor
    @tutor = Tutor.find(params[:id])
  end

  def tutor_params
    params.require(:tutor).permit(:first_name, :last_name, :email, :password)
  end
end

app/controllers/tutors/chats_controller.rb
class Tutors::ChatsController < ApplicationController
  before_action :authenticate_tutor!

  def index
  end

  def show
  end
end

app/helpers/accountants/homeworks_helper.rb
module Accountants::HomeworksHelper
end

app/helpers/admins/homework_helper.rb
module Admins::HomeworkHelper
end

app/helpers/admins/tutors_helper.rb
module Admins::TutorsHelper
end

app/helpers/managers/homeworks_helper.rb
module Managers::HomeworksHelper
end

app/helpers/quality_officers/homeworks_helper.rb
module QualityOfficers::HomeworksHelper
end

app/helpers/tutor/homeworks_helper.rb
module Tutor::HomeworksHelper
end

app/helpers/tutors/chats_helper.rb
module Tutors::ChatsHelper
end

app/views/tutors/homeworks/_for_admin_approval.html.haml
%tr
  %td.text-start= home.id
  %td.text-center=home.name
  %td.text-center= home.created_at.strftime("%B %d, %Y") 
  %td.text-center= home.order_type.titleize
  %td.text-center= home.sub_type.titleize if home.sub_type.present?
  %td.text-center= home.internal_deadline.strftime("%B %d, %Y")
  %td.text-center= home.subject
  %td.text-center= home.words
  -# %td.text-center= home.priority
  -# %td.text-center= home.login_school
  -# %td.text-center= home.hours_late
  -# %td.text-center= home.prof
  -# %td.text-center= home.grade
  %td.text-center= format_category(home)
  %td.text-center= home.status
  %td.text-end
    %a.fas.fa-eye.text-success.font-16.mr-3{href: tutors_homework_path(home)}

app/views/tutors/homeworks/_table.html.haml
%tr
  %td.text-start= home.name
  %td.text-center= home.created_at.strftime("%B %d, %Y") 
  %td.text-center= home.order_type.titleize
  %td.text-center= home.sub_type.titleize
  %td.text-center= home.deadline.strftime("%B %d, %Y")
  %td.text-center= home.subject
  %td.text-center= home.tutor_category.titleize
  %td.text-center= home.words
  %td.text-center= home.priority
  %td.text-center= home.login_school
  %td.text-center= home.user.name
  %td.text-center= home.tutor.name
  %td.text-center= home.sub_tutor.name if home.sub_tutor.present?
  %td.text-center= home.id
  %td.text-center= home.hours_late
  %td.text-center= home.prof
  %td.text-center= home.grade
  %td.text-center= home.status
  -# %td.text-end
  -#   = link_to :show, managers_homework_path(home)

app/views/tutors/homeworks/add_bid.html.haml
= render 'tutors/shared/header'
= render 'tutors/shared/chat-widget'
.row 
  .col-xl-6.col-lg-8.col-md-10.col-sm-12.ms-auto.me-auto 
    .mt-5
      %h4= @homework.order_type.titleize
.row
  .col-xl-6.col-lg-8.col-md-10.col-sm-12.ms-auto.me-auto 
    .card
      .card-body
        .row.mt-3
          .col-6
            -# %h5= "Client: #{@homework.user.name}"
        .row.mt-3
          .col-6
            %h5 Deadline:
            %p= @homework.deadline.strftime("%b %d, %Y - %l:%M %p") if @homework.deadline.present?
          .col-6
            %h5 Subject:
            %p=  @homework.subject.present? ? @homework.subject : "None Provided"
          .col-6
            %h5 Words:
            %p= @homework.words
          .col-6
            %h5 Target Grade:
            %p= @homework.grade


        %hr
        .row 
          .col-xl-6.col-lg-8.col-md-10.col-sm-12.ms-auto.me-auto 
            %h5= "Add Bid #{@homework.order_type.titleize}"
            %h6= "Starting Bid: #{@homework.min_bid}"
        .row
          .col-xl-6.col-lg-8.col-md-10.col-sm-12.ms-auto.me-auto 
            = form_tag(tutors_homework_bid_path) do
              .mb-3
                .field
                  = label_tag "amount", 'Amount', class: "form-label"
                  = number_field_tag 'ammount', nil, {class: "form-control", min: @homework.min_bid, required: true}
              .mb-3
                .actions
                  = submit_tag "Create", class: "btn btn-primary"

app/views/tutors/homeworks/edit_bid.html.haml
= render 'tutors/shared/header'
= render 'tutors/shared/chat-widget'
.row 
  .col-xl-6.col-lg-8.col-md-10.col-sm-12.ms-auto.me-auto 
    .mt-5
      %h4= @homework.order_type.titleize
.row
  .col-xl-6.col-lg-8.col-md-10.col-sm-12.ms-auto.me-auto 
    .card
      .card-body
        .row.mt-3
          .col-6
            -# %h5= "Client: #{@homework.user.name}"
        .row.mt-3
          .col-6
            %h5 Deadline:
            %p= @homework.deadline.strftime("%b %d, %Y - %l:%M %p") if @homework.deadline.present?
          .col-6
            %h5 Subject:
            %p= @homework.subject.present? ? @homework.subject : "None Provided"
          .col-6
            %h5 Words:
            %p= @homework.words
          .col-6
            %h5 Target Grade:
            %p= @homework.grade


        %hr
        .row 
          .col-xl-6.col-lg-8.col-md-10.col-sm-12.ms-auto.me-auto 
            %h5 Edit Bid
        .row
          .col-xl-6.col-lg-8.col-md-10.col-sm-12.ms-auto.me-auto 
            = form_tag(tutors_homework_update_bid_path, method: :put) do
              .mb-3
                .field
                  = label_tag "amount", 'Amount', class: "form-label"
                  = number_field_tag 'ammount', @bid.ammount,{class: "form-control", min: @homework.min_bid, required: true}
              .mb-3
                .actions
                  = submit_tag "Update", class: "btn btn-primary"

app/views/tutors/homeworks/show.html.haml
= render 'tutors/shared/header'
= render 'tutors/shared/chat-widget'
.container-fluid 
  .container
    .row
    -if flash.any?
      .row.text-center
      - flash.each do |type, msg|
        .col-lg-12.col-md-12.col-sm-12.alert.mt-3.mb-3{class: type == "alert" ? "alert-danger" : "alert-success"}
          = msg
    .mt-5
      %h4= @homework.order_type.titleize
.container-fluid 
  .container
    .card
      .card-body
        .row.mt-3
          .col-6
            -# %h5= "Client: #{@homework.user.name}"
          -if @homework.tutor_id == current_tutor.id
            .col-6.text-end
              %button.btn.btn-primary{"data-bs-target" => "#exampleModal", "data-bs-toggle" => "modal", type: "button"}
                Files
              = link_to "Submit for Approval", tutors_homework_finish_homework_path(@homework.id), method: :put, class: "btn btn-success #{'disabled' if @homework.status == 'finished_by_tutor'}"
        .row.mt-3
          .col-6
            %h5 Order Number:
            %p= @homework.id
          .col-6
            %h5 Deadline:
            %p= @homework.internal_deadline
          .col-6
            %h5 Subject:
            %p= @homework.subject_id.present? ? @homework.subject.name : "None Provided"
          .col-6
            %h5 Words:
            %p= @homework.words
          .col-6
            %h5 Target Grade:
            %p= @homework.grade
          .col-6
            %h5 Tutor Category:
            %p= format_category(@homework)
          - if @homework.hw_attachment.attached?
            .row
              .col-12
                %h6 Download file
                - if @manager.present?
                  - @manager.each do |docs|
                    = link_to docs.file.filename, rails_blob_path(docs.file, disposition: 'attachment'), class: "btn btn-success"
                -else 
                  - @homework.hw_attachment.each do |attachment|
                    =link_to attachment.filename, rails_blob_path(attachment, disposition: 'attachment'),class: "btn btn-success" 
        %hr
        .row
          .col-12 
            %h5 Details:
            %p= @homework.details

.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "exampleModalLabel", tabindex: "-1", id: "exampleModal"}
  .modal-dialog.modal-lg
    .modal-content
      .modal-header
        %h5#exampleModalLabel.modal-title= @homework.name
        %button.btn-close{"aria-label" => "Close", "data-bs-dismiss" => "modal", type: "button"}
      =form_for @homework.documents.new, url: tutors_homework_upload_path(homework_id: @homework.id) do |f|
        .modal-body
          .row.d-flex.justify-content-between
            .col-12
              %h5 Upload File
          .row.d-flex.justify-content-between{style:"border:blue; border-style:dashed; margin:auto; padding:35px;"}
            .col-10
              = f.file_field "file", class: "form-control"
            .col-2.text-end
              = submit_tag "Upload", class: "btn btn-primary disabled", id: "uploadButton"
          .row.mt-3
            %h5 Uploaded files:
            .container-flex.mt-2
              - @documents.each do |docu|
                .row.d-flex.justify-content-between
                  .col-3
                    = docu.file.filename
                  .col-3.text-end
                    = link_to "Download File", rails_blob_path(docu.file, disposition: 'attachment'),class: "btn btn-success"
                %hr
        .modal-footer
          %button.btn.btn-secondary{"data-bs-dismiss" => "modal", type: "button"} Close

- if @homework.tutor_id != current_tutor.id
  .container-fluid
    .container
      .row.my-5
        .col-sm-12.col-md-6.ms-auto.me-auto 
          .card
            .card-body
              .row.mt-3
                .col-6 
                  %h5= "Tutors Interested: #{@bids.count}"
                  %h6= "Starting Bid: #{@homework.min_bid}"
                .col-6.text-end
                  - if @bid.present?
                    = link_to "Update Bid - #{@bid.ammount}", tutors_homework_edit_bid_path(@homework.id), class: "btn btn-primary"
                  - else 
                    = link_to "Add Bid", tutors_homework_add_bid_path(@homework.id), class: "btn btn-success"
                .col-12
                  .table-responsive
                    %table.table
                      %thead
                        %tr
                          -# %th.text-start Deadline
                          %th.text-start Offer
                      %tbody
                        - unless @bids.blank?
                          - @bids.each do |bid|
                            %tr
                              -# %td.text-start= bid.id
                              %td.text-start= bid.ammount
                        -else
                          %td No Data found

= javascript_pack_tag 'homeworks/tutor'