config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root to: 'pages#home'
  get '/pick_type', to: 'pages#pick_type'
  get '/new', to: 'pages#new'
  get '/professors', to: 'pages#professors'
  get '/professors/:id', to: 'pages#professor_show'
  get '/about_us', to: 'pages#about_us'
  get '/services', to: 'pages#services'
  get '/testimonies', to: 'pages#testimonies'
  get '/how_it_works', to: 'pages#how_it_works'
  get '/contact-us', to: 'pages#contact_us'
  get '/check-email', to: 'pages#check_email'
  get '/how-it-works', to: 'pages#how_it_works'
  get '/pricing', to:'pages#pricing'
  # get '/change-theme', to: 'application#set_theme'
  resources :contacts, only: [:create]

  resources :qnas do
    get :pick_type, on: :collection
    put :finish
    get :cancel
    resources :chats, only: [:show] do
      resources :messages, only: [:create], on: :collection
    end
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/auth/sessions',
    registrations: 'admins/auth/registrations',
    passwords: 'admins/auth/passwords'
  }

  devise_for :tutors, path: 'tutors', controllers: {
    sessions: 'tutors/auth/sessions',
    registrations: 'tutors/auth/registrations',
    passwords: 'tutors/auth/passwords'
  }

  devise_for :managers, path: 'managers', controllers: {
    sessions: 'managers/auth/sessions',
    registrations: 'managers/auth/registrations',
    passwords: 'managers/auth/passwords'
  }

  devise_for :accountants, path: 'accountants', controllers: {
    sessions: 'accountants/auth/sessions',
    registrations: 'accountants/auth/registrations',
    passwords: 'accountants/auth/passwords'
  }

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/auth/sessions',
    registrations: 'users/auth/registrations',
    passwords: 'users/auth/passwords'
  }

  devise_for :quality_officers, path: 'quality_officers', controllers: {
    sessions: 'quality_officers/auth/sessions'
    # registrations: 'quality_officers/auth/registrations',
    # passwords: 'quality_officers/auth/passwords'
  }

  namespace :admins do
    resources :homeworks, except: [:new, :create], on: :collection do
      put :assign
      put :finish_homework
      put :assign_tutor
      post :upload
    end
    resources :professors
    resources :prof_reviews, only: [:show, :update] do
      post :approve
    end
    resources :documents, only: [:index], on: :collection
    resources :managers, on: :collection
    resources :users, on: :collection
    resources :tutors, on: :collection
    resources :accountants, on: :collection
    resources :admins
    resources :chats, only: [:index]
    resources :quality_officers, on: :collection
    resources :qnas, only: [:index, :show], on: :collection do
      get :finish
    end
    get '/', to: 'dashboard#home'
  end

  namespace :quality_officers do
    resources :homeworks, only: [:index, :show] do
      post :upload
    end
    get '/', to: 'dashboard#home'
  end

  namespace :managers do
    resources :homeworks, only: [:index, :show, :update, :edit], on: :collection do
      post :upload
      put :approve
      put :assign_tutor
    end
    resources :chats, only: [:index]
    get '/', to: 'dashboard#home'
  end

  namespace :tutors do
    resources :homeworks, only: [:index, :show], on: :collection do
      get :add_bid
      get :edit_bid
      post :bid
      put :update_bid
      post :upload
      put :finish_homework
    end

    resources :qnas, only: [:index, :show] do
      put :assign
      put :cancel

      resources :messages, only: [:create]
      patch '/add_payment', to: 'qnas#add_payment', as: 'add_payment'
    end

    resources :chats, only: [:index]
    get '/', to: 'homeworks#index'
  end

  namespace :users do
    resources :homeworks, on: :collection do
      get :success
      get :pick_type, on: :collection

      patch '/edit', to: 'homeworks#update', as: 'update_homework'
      get '/submit_homework', to: 'homeworks#submit_homework', as: 'submit_homework'

      get '/delete_draft', to: 'homeworks#delete_draft', as: 'delete_draft'
    end
    post 'homeworks/add_to_draft', to: 'homeworks#add_to_drafts', as: 'add_to_drafts'

    resources :professors, only: [:index, :show, :new, :create] do
      get :search, on: :collection
    end

    resources :qnas do
      get :finish
      get :cancel
      resources :chats, only: [:show] do
        resources :messages, only: [:create], on: :collection
      end
    end

    get 'profile', to: 'users#show'
    resources :chats, only: [:index]
    get '/', to: 'dashboard#home'
  end

  namespace :accountants do
    resources :homeworks, only: [:index, :show, :update], on: :collection
    get '/', to: 'dashboard#home'
  end
  get '/cheko-ai' => 'gpt3#index'
  post '/gpt3/generate' => 'gpt3#generate'
  post '/gpt3/rewrite' => 'gpt3#rewrite'
  post '/gpt3/humanize' => 'gpt3#humanize'
  post '/gpt3/update_title' => 'gpt3#update_title'
  post '/gpt3/update_conversation' => 'gpt3#update_conversation'
  post '/gpt3/save_conversation' => 'gpt3#save_conversation'
  post '/gpt3/delete_conversation' => 'gpt3#delete_conversation'
  get '/gpt3/render_better_answer_bubble' => 'gpt3#render_better_answer_bubble'
end

app/models/professor.rb
class Professor < ApplicationRecord
  has_many :prof_reviews
  belongs_to :school, optional: true

  def name
    return "#{self.first_name} #{self.last_name}"
  end

  def update_grading
    reviews = self.prof_reviews.where(status: "approved")
    approve_count = reviews.count

    easiness = reviews.average(:easiness).to_i
    effectiveness = reviews.average(:effectiveness).to_i
    life_changing = reviews.average(:life_changing).to_i
    light_workload = reviews.average(:light_workload).to_i
    leniency = reviews.average(:leniency).to_i
    
    average = easiness + effectiveness + life_changing + light_workload + leniency
    average = average/5

    hash = {
      easiness: easiness,
      effectiveness: effectiveness,
      life_changing: life_changing,
      light_workload: light_workload,
      leniency: leniency,
      average: average.to_f,
      a_able: reviews.average(:a_able).to_i,
      b_pls_able: reviews.average(:b_pls_able).to_i,
      b_able: reviews.average(:b_able).to_i,
      c_able: reviews.average(:c_able).to_i,
      batch1_able: reviews.average(:batch1_able).to_i,
      batch2_able: reviews.average(:batch2_able).to_i,
      batch3_able: reviews.average(:batch3_able).to_i,
      batch4_able: reviews.average(:batch4_able).to_i
    }

    self.update(hash)
  end

  def set_up_email
    # professor = self.professor

    if self.school.name == "DLSU"
      self.dlsu_email
    elsif self.school.name == "ADMU" 
      self.admu_email
    end
  end

  def admu_email
    fname = self.first_name

    fname.split(" ").each do |name|
      fcharacter = name.first.downcase
      next if Professor.find_by(email: "#{fcharacter}#{self.last_name.downcase}@ateneo.edu")
      self.update!(email: "#{fcharacter}#{self.last_name.downcase}@ateneo.edu")
      break
    end
  end

  def dlsu_email
    new_name = ""
    fname = self.first_name
    fname.split(" ").each_with_index do |name, ind|
      if ind == 0
        new_name.concat(name.downcase)
      else
        new_name.concat(".#{name.downcase}")
      end
    end

    email = "#{new_name}.#{self.last_name.gsub(/\s+/, "").downcase}@dlsu.edu.ph"
    self.update(email: email)
  end
end

app/controllers/admins/professors_controller.rb
class Admins::ProfessorsController < ApplicationController
  before_action :authenticate_admin!
  before_action :find_prof, except: [:index, :new, :create]
  include ProfessorMetricsHelper

  def index
    @professors = Professor.all
    @pending = ProfReview.where(status: "pending")
  end

  def show
  end
  
  def new
    @professor = Professor.new
    @school = School.all
  end

  def create
    @professor = Professor.create(professor_params)

    if @professor.school_id.nil? && params[:school_name].present?
      unless School.where("LOWER(name) = LOWER(?)", params[:school_name]).first
        new_school = School.create(name: params[:school_name])
        @professor.update(school_id: new_school.id)
      end
    end

    redirect_to admins_professors_path
  end

  def edit
  end

  def update
    @professor.update(professor_params)
    redirect_to admins_professor_path(@professor)
  end

  def approve
  end

  def deny
  end

  def destroy
    prof_rev = ProfReview.where(professor_id: @professor.id)
    prof_rev.each do |rev|
      rev.delete()
    end

    @professor.delete()
    redirect_to admins_professors_path()
  end

  private

  def find_prof
    @professor = Professor.find(params[:id] || params[:professor_id])
  end

  def professor_params
    params.require(:professor).permit(:first_name, :last_name, :school_id, :easiness, :effectiveness, :life_changing, :light_workload, :leniency, :average, :a_able, :b_pls_able, :b_able, :c_able, :batch1_able, :batch2_able, :batch3_able, :batch4_able, :our_comments, :additional_metric_grade)
  end
end

app/controllers/users/professors_controller.rb
class Users::ProfessorsController < Users::UserAppController
  before_action :authenticate_user!, except: [:search]
  include ProfessorMetricsHelper
  
  def index
  end

  def show
    @professor = Professor.find(params[:id])
    @reviews = @professor.prof_reviews.where(status: "approved")
  end

  def new
    @professor = params[:prof_id].present? ? Professor.find(params[:prof_id]) : nil
    @prof_review = ProfReview.new
    @school = School.all
  end

  def create 
    # raise "test"
    @prof_review = current_user.prof_reviews.create(professor_params)
    prof = Professor.find_by(first_name: @prof_review.first_name, last_name: @prof_review.last_name)
    if prof
      @prof_review.update(status: "approved", professor_id: prof.id)
      prof.update_grading
      redirect_to users_professors_path
    elsif params[:prof_id].present?
      @professor = current_user.prof_reviews.create(professor_params)
      @professor.update(status: "approved")
      redirect_to users_professors_path
    else
      hash = JSON.parse(@prof_review.to_json)
      hash = hash.except("id", "professor_id", "user_id", "created_at", "updated_at", "status", "content", "school", "school_name")
      new_prof = Professor.create(hash)
      new_prof.update(subject: params[:prof_review][:subject])
      @prof_review.update(status: "approved", professor_id: new_prof)

      if @prof_review.school_id.nil? || @prof_review.school_id == 0 && @prof_review.school_name.present?
        unless School.where("LOWER(name) = LOWER(?)", @prof_review.school).first
          new_school = School.create(name: @prof_review.school_name)
          new_prof.update(school_id: new_school.id)
        end
      end

      if @prof_review.school_id.present?
        new_prof.set_up_email
      end

      if current_user.present?
        user = current_user
        ProfToPickJob.set(wait: 2.seconds).perform_later("review_recieved", user)
      end
      
      redirect_to users_professors_path
    end

    
  end

  def search
    # profs = Professor.all()
    profs = Professor.where("LOWER(first_name) LIKE :search OR LOWER(last_name) LIKE :search", {search: "%#{params[:search].downcase}%"}).map{|prof| [prof.name, prof.id]}
    #.pluck(:first_name, :last_name)
    render json: {profs: profs}
  end

  private
  def professor_params
    params.require(:prof_review).permit(:first_name, :last_name, :school_id, :school_name, :easiness, :effectiveness, :life_changing, :light_workload, :leniency, :average, :a_able, :b_pls_able, :b_able, :c_able, :batch1_able, :batch2_able, :batch3_able, :batch4_able, :content, :subject, :additional_metric_grade, :professor_id)
  end
end

app/helpers/admins/professors_helper.rb
module Admins::ProfessorsHelper
end

app/helpers/users/professors_helper.rb
module Users::ProfessorsHelper
  def options_for_school
    options = School.all.collect {|p| [ p.name, p.id ] }
    options << ['Others', 'others']
    # you can define your own logic for selected value.
    selected = !@professor.nil? ? @professor.school_id : 1
    options_for_select(options, selected)
  end
end

app/views/admins/professors/edit.html.haml
= render 'admins/shared/header'
.container-fluid
  .row
    .col-md-3.col-lg-2
      = render 'admins/shared/sidebar'
    .col-md-9.col-lg-10
      .row 
        .col-xl-8.col-lg-10.col-sm-12.ms-auto.me-auto 
          .container.mt-5
            .card{class: "card card-#{cookies[:theme]}" }  
              .card-body
                .row.mb-3
                  .col-6.text-start.ms-auto.me-auto 
                    %h5 Update Professor
                .row
                  .col-6.ms-auto.me-auto
                    = form_for @professor, url: admins_professor_path, method: :put do |f|
                      .mb-3
                        .field
                          = f.label :first_name, class: "form-label"
                          = f.text_field :first_name, class: "form-control", required: true, value: @professor.first_name
                      .mb-3
                        .field
                          = f.label :last_name, class: "form-label"
                          = f.text_field :last_name, class: "form-control", required: true, value: @professor.last_name
                      .mb-3
                        .field
                          = f.label :school, class: "form-label"
                          = f.select :school_id, School.all.collect {|p| [ p.name, p.id ] }, { selected: @professor.school_id }, class: "form-select"
                      .mb-3
                        .field
                          = f.label :easiness, class: "form-label"
                          %h6#percent= "#{@professor.easiness}%"
                          = f.range_field :easiness, class: "form-range", in: 1..100, value: @professor.easiness
                      .mb-3
                        .field
                          = f.label :effectiveness, class: "form-label"
                          %h6#percent_ef= "#{@professor.effectiveness}%"
                          = f.range_field :effectiveness, class: "form-range", in: 1..100, value: @professor.effectiveness
                      .mb-3
                        .field
                          = f.label :life_changing, class: "form-label"
                          %h6#percent_lf= "#{@professor.life_changing}%"
                          = f.range_field :life_changing, class: "form-range", in: 1..100, value: @professor.life_changing
                      .mb-3
                        .field
                          = f.label :light_workload, class: "form-label"
                          %h6#percent_lw= "#{@professor.light_workload}%"
                          = f.range_field :light_workload, class: "form-range", in: 1..100, value: @professor.light_workload
                      .mb-3
                        .field
                          = f.label :leniency, class: "form-label"
                          %h6#percent_len= "#{@professor.leniency}%"
                          = f.range_field :leniency, class: "form-range", in: 1..100, value: @professor.leniency
                      .mb-3
                        .field.row
                          .col-6
                            -# = f.label :average, class: "form-label"
                            %h2 Average:
                          .col-6 
                            %h2#percent_av= "#{@professor.average}%"
                          = f.hidden_field :average, class: "form-range", id: "professor_average", value: @professor.average
                      %hr
                      .mb-3
                        %h4 Additional Metrics: 
                      .mb-3
                        .field
                          = f.label :a_able, "A-able", class: "form-label"
                          %h6#percent_aable= "#{@professor.a_able}%"
                          = f.range_field :a_able, class: "form-range", in: 1..100, value: @professor.a_able
                      .mb-3
                        .field
                          = f.label :b_pls_able, "B+-able", class: "form-label"
                          %h6#percent_bbable= "#{@professor.b_pls_able}%"
                          = f.range_field :b_pls_able, class: "form-range", in: 1..100, value: @professor.b_pls_able
                      .mb-3
                        .field
                          = f.label :b_able, "B-able", class: "form-label"
                          %h6#percent_bable= "#{@professor.b_able}%"
                          = f.range_field :b_able, class: "form-range", in: 1..100, value: @professor.b_able
                      .mb-3
                        .field
                          = f.label :c_able, "C-able", class: "form-label"
                          %h6#percent_cable= "#{@professor.c_able}%"
                          = f.range_field :c_able, class: "form-range", in: 1..100, value: @professor.c_able
                      %hr
                      .mb-3
                        .field
                          = f.label :batch1_able, "Batch 1-able", class: "form-label"
                          %h6#percent_b1able= "#{@professor.batch1_able}%"
                          = f.range_field :batch1_able, class: "form-range", in: 1..100, value: @professor.batch1_able
                      .mb-3
                        .field
                          = f.label :batch2_able, "Batch 2-able", class: "form-label"
                          %h6#percent_b2able= "#{@professor.batch2_able}%"
                          = f.range_field :batch2_able, class: "form-range", in: 1..100, value: @professor.batch2_able
                      .mb-3
                        .field
                          = f.label :batch3_able, "Batch 3-able", class: "form-label"
                          %h6#percent_b3able= "#{@professor.batch3_able}%"
                          = f.range_field :batch3_able, class: "form-range", in: 1..100, value: @professor.batch3_able
                      .mb-3
                        .field
                          = f.label :batch4_able, "Batch 4-able", class: "form-label"
                          %h6#percent_b4able= "#{@professor.batch4_able}%"
                          = f.range_field :batch4_able, class: "form-range", in: 1..100, value: @professor.batch4_able
                      %hr
                      %h4 Our comment
                      .mb-3
                        .field
                          = f.label :our_comments, class: "form-label"
                          = f.text_area :our_comments, class: "form-control", rows: 10, value: @professor.our_comments
                      .mb-3
                        .actions
                          = f.submit "Update", class: "btn btn-primary"

= javascript_pack_tag 'professors/new'

app/views/admins/professors/index.html.haml
= render 'admins/shared/header'
.container-fluid
  .row
    .col-md-3.col-lg-2
      = render 'admins/shared/sidebar'
    .col-md-9.col-lg-10
      .row 
        .col-xl-8.col-lg-10.col-sm-12.ms-auto.me-auto 
          .container.mt-5
            .card{class: "card card-#{cookies[:theme]}" } 
              .card-body
                .row 
                  .col-6.text-start
                    %h3 Pending
                .table-responsive
                  %table.datatableBasic.display.nowrap
                    %thead
                      %tr
                        %th.text-start id
                        %th.text-center Name
                        %th.text-center School
                        %th.text-end Action
                    %tbody
                      - @pending.each do |prof|
                        %tr
                          %td.text-start= prof.id
                          %td.text-center= prof.name
                          %td.text-center= prof.school_id.present? ? prof.school.name : ""
                          %td.text-end
                            %a.fas.fa-eye.text-success.font-16.mr-3{href: admins_prof_review_path(prof)}
      .row 
        .col-xl-8.col-lg-10.col-sm-12.ms-auto.me-auto 
          .container.mt-5
            .card{class: "card card-#{cookies[:theme]}" }
              .card-body
                .row 
                  .col-6.text-start
                    %h3 Professors
                  .col-6.text-end 
                    = link_to "New Prof", new_admins_professor_path, class: "btn btn-primary"
                .table-responsive
                  %table.datatableBasic.display.nowrap
                    %thead
                      %tr
                        %th.text-start id
                        %th.text-center Name
                        %th.text-center School
                        %th.text-end Action
                    %tbody
                      - @professors.each do |prof|
                        %tr
                          %td.text-start= prof.id
                          %td.text-center= prof.name
                          %td.text-center= prof.school_id.present? ? prof.school.name : ""
                          %td.text-end
                            %a.fas.fa-eye.text-success.font-16.mr-3{href: admins_professor_path(prof)}
                            %a.fas.fa-pen.text-primary.font-16.mr-3{href: edit_admins_professor_path(prof)}
                            = link_to '', admins_professor_path(prof), method: :delete, data: {confirm: "Are you sure?"}, class: "fas fa-trash text-danger font-16 mr-3"
              
= javascript_pack_tag 'datatable_basic'

app/views/admins/professors/new.html.haml
= render 'admins/shared/header'
.row
  .col-md-3.col-lg-2
    = render 'admins/shared/sidebar'
  .col-md-9.col-lg-10
    .row 
      .col-xl-8.col-lg-10.col-sm-12.ms-auto.me-auto 
        .container.mt-5
          .card{class: "card card-#{cookies[:theme]}" }  
            .card-body
              .row.mb-3
                .col-6.text-start.ms-auto.me-auto 
                  %h5 Add Professor
              .row
                .col-6.ms-auto.me-auto
                  = form_for @professor, url: admins_professors_path, method: :post do |f|
                    .mb-3
                      .field
                        = f.label :first_name, class: "form-label"
                        = f.text_field :first_name, class: "form-control", required: true
                    .mb-3
                      .field
                        = f.label :last_name, class: "form-label"
                        = f.text_field :last_name, class: "form-control", required: true
                    .mb-3
                      .field
                        = f.label :school, class: "form-label"
                        = f.select :school_id, School.all.collect {|p| [ p.name, p.id ] }, { include_blank: false }, class: "form-select"
                        #school_string.mt-3{class: "d-none"}
                          %h6 *if school is not in selection, type the school
                          = text_field_tag :school_name, "", class: "form-control", id: "professor_school_name", required: true
                    .mb-3
                      .field
                        = f.label :easiness, class: "form-label"
                        %h6#percent 50%
                        = f.range_field :easiness, class: "form-range", in: 0..100, value: 50
                    .mb-3
                      .field
                        = f.label :effectiveness, class: "form-label"
                        %h6#percent_ef 50%
                        = f.range_field :effectiveness, class: "form-range", in: 0..100, value: 50
                    .mb-3
                      .field
                        = f.label :life_changing, class: "form-label"
                        %h6#percent_lf 50%
                        = f.range_field :life_changing, class: "form-range", in: 0..100, value: 50
                    .mb-3
                      .field
                        = f.label :light_workload, class: "form-label"
                        %h6#percent_lw 50%
                        = f.range_field :light_workload, class: "form-range", in: 0..100, value: 50
                    .mb-3
                      .field
                        = f.label :leniency, class: "form-label"
                        %h6#percent_len 50%
                        = f.range_field :leniency, class: "form-range", in: 0..100, value: 50
                    .mb-3
                      .field.row
                        .col-6
                          -# = f.label :average, class: "form-label"
                          %h2 Average:
                        .col-6 
                          %h2#percent_av 50%
                        = f.hidden_field :average, class: "form-range", id: "professor_average"
                    %hr
                    .mb-3
                      %h4 Additional Metrics: 
                    .mb-3
                      .field
                        %h6#additional_metric B 
                        =f.range_field :additional_metric_grade, class: "form-range", in: 0..100, step: 25, value: 50
                    -# .mb-3
                    -#   .field
                    -#     = f.label :a_able, "A-able", class: "form-label"
                    -#     %h6#percent_aable 50%
                    -#     = f.range_field :a_able, class: "form-range", in: 0..100
                    -# .mb-3
                    -#   .field
                    -#     = f.label :b_pls_able, "B+-able", class: "form-label"
                    -#     %h6#percent_bbable 50%
                    -#     = f.range_field :b_pls_able, class: "form-range", in: 1..100
                    -# .mb-3
                    -#   .field
                    -#     = f.label :b_able, "B-able", class: "form-label"
                    -#     %h6#percent_bable 50%
                    -#     = f.range_field :b_able, class: "form-range", in: 1..100
                    -# .mb-3
                    -#   .field
                    -#     = f.label :c_able, "C-able", class: "form-label"
                    -#     %h6#percent_cable 50%
                    -#     = f.range_field :c_able, class: "form-range", in: 1..100
                    %hr
                    -# .mb-3
                    -#   .field
                    -#     = f.label :batch1_able, "Batch 1-able", class: "form-label"
                    -#     %h6#percent_b1able 50%
                    -#     = f.range_field :batch1_able, class: "form-range", in: 1..100
                    -# .mb-3
                    -#   .field
                    -#     = f.label :batch2_able, "Batch 2-able", class: "form-label"
                    -#     %h6#percent_b2able 50%
                    -#     = f.range_field :batch2_able, class: "form-range", in: 1..100
                    -# .mb-3
                    -#   .field
                    -#     = f.label :batch3_able, "Batch 3-able", class: "form-label"
                    -#     %h6#percent_b3able 50%
                    -#     = f.range_field :batch3_able, class: "form-range", in: 1..100
                    -# .mb-3
                    -#   .field
                    -#     = f.label :batch4_able, "Batch 4-able", class: "form-label"
                    -#     %h6#percent_b4able 50%
                    -#     = f.range_field :batch4_able, class: "form-range", in: 1..100
                    -# %hr
                    %h4 Our comment
                    .mb-3
                      .field
                        = f.label :our_comments, class: "form-label"
                        = f.text_area :our_comments, class: "form-control", rows: 10
                    .mb-3
                      .actions
                        = f.submit "Create", class: "btn btn-primary"

= javascript_pack_tag 'professors/new'