config/routes.rb
Rails.application.routes.draw do
  mount ActionCable.server => '/cable'

  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'

  root to: 'pages#home'
  get '/pick_type', to: 'pages#pick_type'
  get '/new', to: 'pages#new'
  get '/professors', to: 'pages#professors'
  get '/professors/:id', to: 'pages#professor_show'
  get '/about_us', to: 'pages#about_us'
  get '/services', to: 'pages#services'
  get '/testimonies', to: 'pages#testimonies'
  get '/how_it_works', to: 'pages#how_it_works'
  get '/contact-us', to: 'pages#contact_us'
  get '/check-email', to: 'pages#check_email'
  get '/how-it-works', to: 'pages#how_it_works'
  get '/pricing', to:'pages#pricing'
  # get '/change-theme', to: 'application#set_theme'
  resources :contacts, only: [:create]

  resources :qnas do
    get :pick_type, on: :collection
    put :finish
    get :cancel
    resources :chats, only: [:show] do
      resources :messages, only: [:create], on: :collection
    end
  end

  devise_for :admins, path: 'admins', controllers: {
    sessions: 'admins/auth/sessions',
    registrations: 'admins/auth/registrations',
    passwords: 'admins/auth/passwords'
  }

  devise_for :tutors, path: 'tutors', controllers: {
    sessions: 'tutors/auth/sessions',
    registrations: 'tutors/auth/registrations',
    passwords: 'tutors/auth/passwords'
  }

  devise_for :managers, path: 'managers', controllers: {
    sessions: 'managers/auth/sessions',
    registrations: 'managers/auth/registrations',
    passwords: 'managers/auth/passwords'
  }

  devise_for :accountants, path: 'accountants', controllers: {
    sessions: 'accountants/auth/sessions',
    registrations: 'accountants/auth/registrations',
    passwords: 'accountants/auth/passwords'
  }

  devise_for :users, path: 'users', controllers: {
    sessions: 'users/auth/sessions',
    registrations: 'users/auth/registrations',
    passwords: 'users/auth/passwords'
  }

  devise_for :quality_officers, path: 'quality_officers', controllers: {
    sessions: 'quality_officers/auth/sessions'
    # registrations: 'quality_officers/auth/registrations',
    # passwords: 'quality_officers/auth/passwords'
  }

  namespace :admins do
    resources :homeworks, except: [:new, :create], on: :collection do
      put :assign
      put :finish_homework
      put :assign_tutor
      post :upload
    end
    resources :professors
    resources :prof_reviews, only: [:show, :update] do
      post :approve
    end
    resources :documents, only: [:index], on: :collection
    resources :managers, on: :collection
    resources :users, on: :collection
    resources :tutors, on: :collection
    resources :accountants, on: :collection
    resources :admins
    resources :chats, only: [:index]
    resources :quality_officers, on: :collection
    resources :qnas, only: [:index, :show], on: :collection do
      get :finish
    end
    get '/', to: 'dashboard#home'
  end

  namespace :quality_officers do
    resources :homeworks, only: [:index, :show] do
      post :upload
    end
    get '/', to: 'dashboard#home'
  end

  namespace :managers do
    resources :homeworks, only: [:index, :show, :update, :edit], on: :collection do
      post :upload
      put :approve
      put :assign_tutor
    end
    resources :chats, only: [:index]
    get '/', to: 'dashboard#home'
  end

  namespace :tutors do
    resources :homeworks, only: [:index, :show], on: :collection do
      get :add_bid
      get :edit_bid
      post :bid
      put :update_bid
      post :upload
      put :finish_homework
    end

    resources :qnas, only: [:index, :show] do
      put :assign
      put :cancel

      resources :messages, only: [:create]
      patch '/add_payment', to: 'qnas#add_payment', as: 'add_payment'
    end

    resources :chats, only: [:index]
    get '/', to: 'homeworks#index'
  end

  namespace :users do
    resources :homeworks, on: :collection do
      get :success
      get :pick_type, on: :collection

      patch '/edit', to: 'homeworks#update', as: 'update_homework'
      get '/submit_homework', to: 'homeworks#submit_homework', as: 'submit_homework'

      get '/delete_draft', to: 'homeworks#delete_draft', as: 'delete_draft'
    end
    post 'homeworks/add_to_draft', to: 'homeworks#add_to_drafts', as: 'add_to_drafts'

    resources :professors, only: [:index, :show, :new, :create] do
      get :search, on: :collection
    end

    resources :qnas do
      get :finish
      get :cancel
      resources :chats, only: [:show] do
        resources :messages, only: [:create], on: :collection
      end
    end

    get 'profile', to: 'users#show'
    resources :chats, only: [:index]
    get '/', to: 'dashboard#home'
  end

  namespace :accountants do
    resources :homeworks, only: [:index, :show, :update], on: :collection
    get '/', to: 'dashboard#home'
  end
  get '/cheko-ai' => 'gpt3#index'
  post '/gpt3/generate' => 'gpt3#generate'
  post '/gpt3/rewrite' => 'gpt3#rewrite'
  post '/gpt3/humanize' => 'gpt3#humanize'
  post '/gpt3/update_title' => 'gpt3#update_title'
  post '/gpt3/update_conversation' => 'gpt3#update_conversation'
  post '/gpt3/save_conversation' => 'gpt3#save_conversation'
  post '/gpt3/delete_conversation' => 'gpt3#delete_conversation'
  get '/gpt3/render_better_answer_bubble' => 'gpt3#render_better_answer_bubble'
end

app/views/admins/admins/edit.html.haml
= render 'admins/shared/header'
= render 'admins/shared/sidebar'
.row 
  .col-xl-8.col-lg-10.col-sm-12.ms-auto.me-auto 
    .container.mt-5
      .card{class: "card card-#{cookies[:theme]}" }  
        .card-body
          .row 
            .col-12.text-start 
              %h5 Update Team Lead
            .col-6.ms-auto.me-auto
              = form_for @admin, url: admins_admin_path, method: :put do |f|
                .mb-3
                  .field
                    = f.label :first_name, class: "form-label"
                    = f.text_field :first_name, class: "form-control", required: true
                .mb-3
                  .field
                    = f.label :last_name, class: "form-label"
                    = f.text_field :last_name, class: "form-control", required: true
                -# .mb-3
                -#   .field
                -#     = f.label :email, class: "form-label"
                -#     = f.email_field :email, class: "form-control", required: true
                -# .mb-3
                -#   .field
                -#     = f.label :password, class: "form-label"
                -#     = f.password_field :password, class: "form-control", required: true
                .mb-3
                  .actions
                    = f.submit "Update", class: "btn btn-primary"
= javascript_pack_tag 'admins/new'

app/views/admins/admins/index.html.haml
= render 'admins/shared/header'
.container-fluid
  .row
    .col-md-3.col-lg-2
      = render 'admins/shared/sidebar'
    .col-md-9.col-lg-10 
      .col-xl-8.col-lg-10.col-sm-12.ms-auto.me-auto 
        .container-flex.mt-5
          .card{class: "card card-#{cookies[:theme]}" }
            .card-body
              .row 
                .col-6.text-start
                  %h3 Leads
                .col-6.text-end 
                  = link_to "New admin", new_admins_admin_path, class: "btn btn-primary"
              .table-responsive
                %table.datatableBasic.display.nowrap
                  %thead
                    %tr
                      %th.text-start id
                      %th.text-center Name
                      %th.text-center Email
                      %th.text-center Role
                      %th.text-end Action
                  %tbody
                    - unless @admins.blank?
                      - @admins.each do |admin|
                        %tr
                          %td.text-start= admin.id
                          %td.text-center= admin.name
                          %td.text-center= admin.email 
                          %td.text-center= admin.role.titleize
                          %td.text-end
                            %a.fas.fa-eye.text-success.font-16.mr-3{href: admins_admin_path(admin)}
                            %a.fas.fa-pen.text-primary.font-16.mr-3{href: edit_admins_admin_path(admin)}
                            = link_to '', admins_admin_path(admin), method: :delete, data: {confirm: "Are you sure?"}, class: "fas fa-trash text-danger font-16 mr-3"
                    -else
                      %td No Data found

= javascript_pack_tag 'datatable_basic'

app/views/admins/admins/new.html.haml
= render 'admins/shared/header'
= render 'admins/shared/sidebar'
.row 
  .col-xl-8.col-lg-10.col-sm-12.ms-auto.me-auto 
    .container.mt-5
      .card{class: "card card-#{cookies[:theme]}" }  
        .card-body
          .row 
            .col-12.text-start 
              %h5 Add Team Lead
            .col-6.ms-auto.me-auto
              = form_for @admin, url: admins_admins_path, method: :post do |f|
                .mb-3
                  .field
                    = f.label :first_name, class: "form-label"
                    = f.text_field :first_name, class: "form-control", required: true
                .mb-3
                  .field
                    = f.label :last_name, class: "form-label"
                    = f.text_field :last_name, class: "form-control", required: true
                .mb-3
                  .field
                    = f.label :email, class: "form-label"
                    = f.email_field :email, class: "form-control", required: true
                .mb-3
                  .field
                    = f.label :password, class: "form-label"
                    = f.password_field :password, class: "form-control", required: true
                .mb-3
                  .actions
                    = f.submit "Create", class: "btn btn-primary"

app/views/admins/admins/show.html.haml
= render 'admins/shared/header'
= render 'admins/shared/sidebar'
.row 
  .col-xl-8.col-lg-10.col-sm-12.ms-auto.me-auto 
    .container.mt-5
      %h4= @admin.name